export type InternationalPaymentCardsList = {
  [productId: number]: {
    blockList: string[]; // 2 letter List of countries that are blocked from minting
    allowList: string[];
  };
};
export const intlPaymentCardsList: InternationalPaymentCardsList = {
  20307: {
    blockList: ["CF", "CD", "ER", "ET", "LY", "ML", "SO", "SS", "SD", "ZW", "CU", "NI", "VE", "AF", "MM", "KP", "SY", "YE", "AL", "BY", "RU", "UA", "FJ"],
    allowList: [
      "DZ",
      "AO",
      "CM",
      "EG",
      "GH",
      "KE",
      "MW",
      "MA",
      "MZ",
      "NG",
      "ZA",
      "TN",
      "ZM",
      "AR",
      "BO",
      "BR",
      "CA",
      "CL",
      "CO",
      "CR",
      "EC",
      "SV",
      "GT",
      "GA",
      "HN",
      "JM",
      "MX",
      "PA",
      "PY",
      "PE",
      "PR",
      "TT",
      "US",
      "UM",
      "UY",
      "GE",
      "IL",
      "JO",
      "KW",
      "MY",
      "NP",
      "OM",
      "PK",
      "PH",
      "QA",
      "SA",
      "SG",
      "KR",
      "TW",
      "TH",
      "TR",
      "AT",
      "BE",
      "CY",
      "CZ",
      "DK",
      "EE",
      "FI",
      "FR",
      "DE",
      "GR",
      "HU",
      "IS",
      "IE",
      "IT",
      "LT",
      "LU",
      "MT",
      "NL",
      "NO",
      "PL",
      "PT",
      "RO",
      "SK",
      "SI",
      "ES",
      "SE",
      "GB",
      "AU",
      "NZ",
      "PG",
      "VU",
    ],
  },
  20316: {
    blockList: [
      "CN",
      "KP",
      "IR",
      "SY",
      "UA",
      "BS",
      "BB",
      "BJ",
      "BI",
      "BF",
      "KH",
      "KY",
      "TD",
      "CF",
      "CG",
      "KM",
      "DO",
      "CU",
      "GN",
      "ER",
      "GW",
      "HT",
      "IQ",
      "LB",
      "LA",
      "LS",
      "MM",
      "MG",
      "NI",
      "NG",
      "PA",
      "SO",
      "SD",
      "SS",
      "UG",
      "VE",
      "YE",
      "ZW",
      "LR",
    ],
    allowList: [],
  },
  20305: {
    blockList: ["CF", "CD", "ER", "ET", "LY", "ML", "SO", "SS", "SD", "ZW", "CU", "NI", "VE", "AF", "MM", "KP", "SY", "YE", "AL", "BY", "RU", "UA", "FJ"],
    allowList: [
      "DZ",
      "AO",
      "CM",
      "EG",
      "GH",
      "KE",
      "MW",
      "MA",
      "MZ",
      "NG",
      "ZA",
      "TN",
      "ZM",
      "AR",
      "BO",
      "BR",
      "CA",
      "CL",
      "CO",
      "CR",
      "EC",
      "SV",
      "GT",
      "GA",
      "HN",
      "JM",
      "MX",
      "PA",
      "PY",
      "PE",
      "PR",
      "TT",
      "US",
      "UM",
      "UY",
      "GE",
      "IL",
      "JO",
      "KW",
      "MY",
      "NP",
      "OM",
      "PK",
      "PH",
      "QA",
      "SA",
      "SG",
      "KR",
      "TW",
      "TH",
      "TR",
      "AT",
      "BE",
      "CY",
      "CZ",
      "DK",
      "EE",
      "FI",
      "FR",
      "DE",
      "GR",
      "HU",
      "IS",
      "IE",
      "IT",
      "LT",
      "LU",
      "MT",
      "NL",
      "NO",
      "PL",
      "PT",
      "RO",
      "SK",
      "SI",
      "ES",
      "SE",
      "GB",
      "AU",
      "NZ",
      "PG",
      "VU",
    ],
  },
  20312: {
    blockList: [
      "AF",
      "IR",
      "IQ",
      "SY",
      "LB",
      "SA",
      "YE",
      "KP",
      "MM",
      "PS", // Palestine / West Bank
      "CF",
      "CD",
      "ET",
      "LY",
      "ML",
      "SO",
      "SS",
      "SD",
      "ZW",
      "AL",
      "BA", // Bosnia and Herzegovina
      "RS", // Serbia
      "ME", // Montenegro
      "HR", // Croatia
      "BY",
      "RU",
      "UA",
      "TR",
      "CU",
      "NI",
      "VE",
    ],
    allowList: [],
  },
  20311: {
    blockList: [
      "AF",
      "IR",
      "IQ",
      "SY",
      "LB",
      "SA",
      "YE",
      "KP",
      "MM",
      "PS", // Palestine / West Bank
      "CF",
      "CD",
      "ET",
      "LY",
      "ML",
      "SO",
      "SS",
      "SD",
      "ZW",
      "AL",
      "BA", // Bosnia and Herzegovina
      "RS", // Serbia
      "ME", // Montenegro
      "HR", // Croatia
      "BY",
      "RU",
      "UA",
      "TR",
      "CU",
      "NI",
      "VE",
    ],
    allowList: [],
  },
  20310: {
    blockList: [
      "AF",
      "IR",
      "IQ",
      "SY",
      "LB",
      "SA",
      "YE",
      "KP",
      "MM",
      "PS", // Palestine / West Bank
      "CF",
      "CD",
      "ET",
      "LY",
      "ML",
      "SO",
      "SS",
      "SD",
      "ZW",
      "AL",
      "BA", // Bosnia and Herzegovina
      "RS", // Serbia
      "ME", // Montenegro
      "HR", // Croatia
      "BY",
      "RU",
      "UA",
      "TR",
      "CU",
      "NI",
      "VE",
    ],
    allowList: [],
  },
  18808: {
    blockList: [
      "AF",
      "BY",
      "MM",
      "CF",
      "CU",
      "CD",
      "EG",
      "ER",
      "GN",
      "GW",
      "IQ",
      "IR",
      "CI",
      "LB",
      "LR",
      "LY",
      "KP",
      "UA",
      "RU",
      "SD",
      "SO",
      "SY",
      "TN",
      "ZW",
      "SS",
    ],
    allowList: [],
  },
};

export function isGeoRestricted(productId: number, countryCode: string): boolean {
  const product = intlPaymentCardsList[productId];

  // If product doesn't exist, it's not geo-restricted (returns false).
  // Otherwise, it's geo-restricted if it's in the blockList
  // OR if it has an allowList and the countryCode is NOT in the allowList.
  return (
    !!product && // Ensure product exists before accessing its properties
    ((product.blockList.length > 0 && product.blockList.includes(countryCode)) || (product.allowList.length > 0 && !product.allowList.includes(countryCode)))
  );
}

export function isAllowed(countryCode: string): boolean {
  /**
   * There are separate allow list for visa & mastercard
   * But right now, both lists contain same countries
   */
  const allowedCountries: Record<string, string> = {
    GP: "Guadeloupe",
    AO: "Angola",
    KI: "Kiribati",
    CA: "Canada",
    CM: "Cameroon",
    QA: "Qatar",
    VU: "Vanuatu",
    EC: "Ecuador",
    AE: "United Arab Emirates",
    KZ: "Kazakhstan",
    GI: "Gibraltar",
    ID: "Indonesia",
    BG: "Bulgaria",
    BE: "Belgium",
    CO: "Colombia",
    BR: "Brazil",
    IT: "Italy",
    EG: "Egypt",
    KR: "South Korea",
    ZA: "South Africa",
    OM: "Oman",
    NF: "Norfolk Island",
    SK: "Slovak Republic",
    SB: "Solomon Islands",
    LU: "Luxembourg",
    //cspell:disable-next-line
    BV: "Bouvet Island",
    GG: "Guernsey",
    GD: "Grenada",
    AW: "Aruba",
    JM: "Jamaica",
    GF: "French Guiana",
    NO: "Norway",
    LI: "Liechtenstein",
    HK: "Hong Kong",
    HU: "Hungary",
    PE: "Peru",
    AM: "Armenia",
    NL: "Netherlands",
    BN: "Brunei Darussalam",
    BM: "Bermuda",
    VI: "Virgin Islands (U.S.)",
    MS: "Montserrat",
    GY: "Guyana",
    DJ: "Djibouti",
    PL: "Poland",
    DK: "Denmark",
    FM: "Federated States of Micronesia",
    GH: "Ghana",
    AD: "Andorra",
    PF: "French Polynesia",
    LV: "Latvia",
    AZ: "Azerbaijan",
    TO: "Tonga",
    CC: "Cocos (Keeling) Islands",
    MR: "Mauritania",
    IL: "Israel",
    GB: "UK",
    LT: "Lithuania",
    CL: "Chile",
    DE: "Germany",
    IN: "India",
    BW: "Botswana",
    IS: "Iceland",
    FI: "Finland",
    BH: "Bahrain",
    US: "USA",
    AI: "Anguilla",
    CZ: "Czech Republic",
    ES: "Spain",
    MT: "Malta",
    SG: "Singapore",
    DZ: "Algeria",
    CY: "Cyprus",
    YT: "Mayotte",
    MP: "Northern Mariana Islands",
    HR: "Croatia",
    CK: "Cook Islands",
    GL: "Greenland",
    SA: "Saudi Arabia",
    GT: "Guatemala",
    MY: "Malaysia",
    JO: "Jordan",
    IE: "Ireland",
    CX: "Christmas Island",
    RO: "Romania",
    NZ: "New Zealand",
    SV: "El Salvador",
    FR: "France",
    KE: "Kenya",
    DM: "Dominica",
    MA: "Morocco",
    TW: "Taiwan",
    NU: "Niue",
    JP: "Japan",
    PH: "Philippines",
    GE: "Georgia",
    GU: "Guam",
    PW: "Palau",
    AU: "Australia",
    AS: "American Samoa",
    //cspell:disable-next-line
    CR: "Costa Rica",
    GM: "Gambia",
    TH: "Thailand",
    //cspell:disable-next-line
    CW: "Curaçao",
    MQ: "Martinique",
    PR: "Puerto Rico",
    BQ: "Caribbean Netherlands",
    BZ: "Belize",
    MW: "Malawi",
    NE: "Niger",
    SI: "Slovenia",
    AT: "Austria",
    MX: "Mexico",
    LK: "Sri lanka",
    PT: "Portugal",
    FK: "Falkland Islands",
    UY: "Uruguay",
    IO: "British Indian Ocean Territory",
    GR: "Greece",
    VA: "Vatican City",
    AQ: "Antarctica",
    FO: "Faroe Islands",
    EE: "Estonia",
    TV: "Tuvalu",
    TF: "French Southern Territories",
    SE: "Sweden",
    AG: "Antigua and Barbuda",
    BO: "Bolivia",
    GA: "Gabon",
    TM: "Turkmenistan",
    AR: "Argentina",
    JE: "Jersey",
    //cspell:disable-next-line
    CV: "Cabo Verde",
    HM: "Heard Island and McDonald Islands",
    BD: "Bangladesh",
    BT: "Bhutan",
    FJ: "Fiji",
    CH: "Switzerland",
    MC: "Monaco",
  };

  return Object.hasOwn(allowedCountries, countryCode);
}

export type CountryList = {
  [key: string]: string;
};

export const allCountries: CountryList = {
  AF: "Afghanistan",
  AX: "Aland Islands",
  AL: "Albania",
  DZ: "Algeria",
  AS: "American Samoa",
  AD: "Andorra",
  AO: "Angola",
  AI: "Anguilla",
  AQ: "Antarctica",
  AG: "Antigua And Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia",
  BA: "Bosnia And Herzegovina",
  BW: "Botswana",
  BV: "Bouvet Island",
  BR: "Brazil",
  IO: "British Indian Ocean Territory",
  BN: "Brunei Darussalam",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  CV: "Cape Verde",
  KY: "Cayman Islands",
  CF: "Central African Republic",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CX: "Christmas Island",
  CC: "Cocos (Keeling) Islands",
  CO: "Colombia",
  KM: "Comoros",
  CG: "Congo",
  CD: "Congo, Democratic Republic",
  CK: "Cook Islands",
  CR: "Costa Rica",
  CI: "Cote D'Ivoire",
  HR: "Croatia",
  CU: "Cuba",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  ET: "Ethiopia",
  FK: "Falkland Islands (Malvinas)",
  FO: "Faroe Islands",
  FJ: "Fiji",
  FI: "Finland",
  FR: "France",
  GF: "French Guiana",
  PF: "French Polynesia",
  TF: "French Southern Territories",
  GA: "Gabon",
  GM: "Gambia",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GI: "Gibraltar",
  GR: "Greece",
  GL: "Greenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GU: "Guam",
  GT: "Guatemala",
  GG: "Guernsey",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HT: "Haiti",
  HM: "Heard Island & Mcdonald Islands",
  VA: "Holy See (Vatican City State)",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran, Islamic Republic Of",
  IQ: "Iraq",
  IE: "Ireland",
  IM: "Isle Of Man",
  IL: "Israel",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  JE: "Jersey",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  KR: "Korea",
  KP: "Korea, Democratic People's Republic Of",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Lao People's Democratic Republic",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libyan Arab Jamahiriya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macao",
  MK: "Macedonia",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MU: "Mauritius",
  YT: "Mayotte",
  MX: "Mexico",
  FM: "Micronesia, Federated States Of",
  MD: "Moldova",
  MC: "Monaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MS: "Montserrat",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands",
  AN: "Netherlands Antilles",
  NC: "New Caledonia",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NE: "Niger",
  NG: "Nigeria",
  NU: "Niue",
  NF: "Norfolk Island",
  MP: "Northern Mariana Islands",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestinian Territory, Occupied",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PN: "Pitcairn",
  PL: "Poland",
  PT: "Portugal",
  PR: "Puerto Rico",
  QA: "Qatar",
  RE: "Reunion",
  RO: "Romania",
  RU: "Russian Federation",
  RW: "Rwanda",
  BL: "Saint Barthelemy",
  SH: "Saint Helena",
  KN: "Saint Kitts And Nevis",
  LC: "Saint Lucia",
  MF: "Saint Martin",
  PM: "Saint Pierre And Miquelon",
  VC: "Saint Vincent And Grenadines",
  WS: "Samoa",
  SM: "San Marino",
  ST: "Sao Tome And Principe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SK: "Slovakia",
  SI: "Slovenia",
  SB: "Solomon Islands",
  SO: "Somalia",
  ZA: "South Africa",
  GS: "South Georgia And Sandwich Isl.",
  ES: "Spain",
  LK: "Sri Lanka",
  SD: "Sudan",
  SR: "Suriname",
  SJ: "Svalbard And Jan Mayen",
  SZ: "Swaziland",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syrian Arab Republic",
  TW: "Taiwan",
  TJ: "Tajikistan",
  TZ: "Tanzania, United Republic Of",
  TH: "Thailand",
  TL: "Timor-Leste",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinidad And Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  TC: "Turks And Caicos Islands",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  GB: "United Kingdom",
  US: "United States",
  UM: "United States Minor Outlying Islands",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VE: "Venezuela",
  VN: "Viet Nam",
  VG: "Virgin Islands, British",
  VI: "Virgin Islands, U.S.",
  WF: "Wallis And Futuna",
  EH: "Western Sahara",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};
