export const dummyCard = {
  productId: 20307,
  productName: "Mastercard Prepaid $150.01 to $2500 US",
  global: false,
  status: "ACTIVE",
  supportsPreOrder: false,
  senderFee: 0,
  senderFeePercentage: 3,
  discountPercentage: 0,
  denominationType: "RANGE",
  recipientCurrencyCode: "USD",
  minRecipientDenomination: 150.01,
  maxRecipientDenomination: 2500,
  senderCurrencyCode: "USD",
  minSenderDenomination: 150.01,
  maxSenderDenomination: 2500,
  fixedRecipientDenominations: [],
  fixedSenderDenominations: null,
  fixedRecipientToSenderDenominationsMap: null,
  metadata: null,
  logoUrls: ["https://cdn.reloadly.com/giftcards/19993571-f35e-4b45-bdd7-28acf6c5183c.png"],
  brand: { brandId: 378, brandName: "Mastercard" },
  category: { id: 1, name: "Payment Cards" },
  country: { isoName: "US", name: "United States", flagUrl: "https://s3.amazonaws.com/rld-flags/us.svg" },
  redeemInstruction: {
    concise: "Description:\nUse your Prepaid Mastercard anywhere Mastercard is accepted around the world. 6-month expiration. Digital or physical card.",
    verbose:
      "Description:\nUse your Prepaid Mastercard anywhere Mastercard is accepted around the world. 6-month expiration. Digital or physical card.\n\nTerms & Condition:\nUse your card anywhere Mastercard is accepted. This card is issued by The Bancorp Bank, N.A., pursuant to license by Mastercard International. Mastercard and the circles design are registered trademarks of Mastercard International Incorporated. The Bancorp Bank, N.A.; Member FDIC. This is not a gift card. This card is issued for loyalty, award or promotional purposes.\n\nBancorp may request additional KYC from time to time.\n\nUSD Issuance Approved Countries:\n\n Africa:\n Algeria, Angola, Cameroon, Egypt, Ghana, Kenya, Malawi, Morocco, Mozambique, Nigeria, South Africa, Tunisia, Zambia\nAmericas:\n Argentina, Bolivia, Brazil (Mastercard only), Canada, Chile, Colombia, Costa Rica, Ecuador, El Salvador, Guatemala, Honduras, Jamaica, Mexico, Paraguay, Peru, Puerto Rico, Trinidad and Tobago, United States (including Minor Outlying Islands), Uruguay\nAsia:\n Georgia, Israel, Jordan, Kuwait, Lebanon, Malaysia, Nepal, Oman, Pakistan, Philippines, Qatar, Saudi Arabia, Singapore, South Korea, Taiwan, Thailand, Turkey\nEurope:\n Austria, Belgium, Cyprus, Czech Republic, Denmark, Estonia, Finland, France, Germany, Greece, Hungary, Iceland, Ireland, Italy, Lithuania, Luxembourg, Malta, Netherlands, Norway, Poland, Portugal, Romania, Slovakia, Slovenia, Spain, Sweden, United Kingdom\nOceania:\n Australia, New Zealand, Papua New Guinea, Vanuatu\n\n USD Issuance Restricted Countries:\n\nAfrica:\n Central African Republic, Democratic Republic of the Congo, Eritrea, Ethiopia, Libya, Mali, Somalia, South Sudan, Sudan, Zimbabwe\nAmericas:\n Cuba, Nicaragua, Venezuela\nAsia:\n Afghanistan, Burma / Myanmar, Lebanon, North Korea, Syria, Yemen\nEurope:\n Albania, Belarus, Russia, Ukraine\nOceania:\n Fiji\nSouth America Exception:\n Brazil (Visa only)",
  },
  additionalRequirements: { userIdRequired: false },
};
