export const dummyCard = {
  productId: 20307,
  productName: "Mastercard Prepaid $150.01 to $2500 US",
  global: false,
  status: "ACTIVE",
  supportsPreOrder: false,
  senderFee: 0,
  senderFeePercentage: 3,
  discountPercentage: 0,
  denominationType: "RANGE",
  recipientCurrencyCode: "USD",
  minRecipientDenomination: 150.01,
  maxRecipientDenomination: 2500,
  senderCurrencyCode: "USD",
  minSenderDenomination: 150.01,
  maxSenderDenomination: 2500,
  fixedRecipientDenominations: [],
  fixedSenderDenominations: null,
  fixedRecipientToSenderDenominationsMap: null,
  metadata: null,
  logoUrls: ["https://cdn.reloadly.com/giftcards/19993571-f35e-4b45-bdd7-28acf6c5183c.png"],
  brand: { brandId: 378, brandName: "Mastercard" },
  category: { id: 1, name: "Payment Cards" },
  country: { isoName: "US", name: "United States", flagUrl: "https://s3.amazonaws.com/rld-flags/us.svg" },
  redeemInstruction: {
    concise: "Description:\nUse your Prepaid Mastercard anywhere Mastercard is accepted around the world. 6-month expiration. Digital or physical card.",
    verbose:
      "Description:\nUse your Prepaid Mastercard anywhere Mastercard is accepted around the world. 6-month expiration. Digital or physical card.\n\nTerms & Condition:\nUse your card anywhere Mastercard is accepted. This card is issued by The Bancorp Bank, N.A., pursuant to license by Mastercard International. Mastercard and the circles design are registered trademarks of Mastercard International Incorporated. The Bancorp Bank, N.A.; Member FDIC. This is not a gift card. This card is issued for loyalty, award or promotional purposes.\n\nBancorp may request additional KYC from time to time.\n\nUSD Issuance Approved Countries:\n\n Africa:\n Algeria, Angola, Cameroon, Egypt, Ghana, Kenya, Malawi, Morocco, Mozambique, Nigeria, South Africa, Tunisia, Zambia\nAmericas:\n Argentina, Bolivia, Brazil (Mastercard only), Canada, Chile, Colombia, Costa Rica, Ecuador, El Salvador, Guatemala, Honduras, Jamaica, Mexico, Paraguay, Peru, Puerto Rico, Trinidad and Tobago, United States (including Minor Outlying Islands), Uruguay\nAsia:\n Georgia, Israel, Jordan, Kuwait, Lebanon, Malaysia, Nepal, Oman, Pakistan, Philippines, Qatar, Saudi Arabia, Singapore, South Korea, Taiwan, Thailand, Turkey\nEurope:\n Austria, Belgium, Cyprus, Czech Republic, Denmark, Estonia, Finland, France, Germany, Greece, Hungary, Iceland, Ireland, Italy, Lithuania, Luxembourg, Malta, Netherlands, Norway, Poland, Portugal, Romania, Slovakia, Slovenia, Spain, Sweden, United Kingdom\nOceania:\n Australia, New Zealand, Papua New Guinea, Vanuatu\n\n USD Issuance Restricted Countries:\n\nAfrica:\n Central African Republic, Democratic Republic of the Congo, Eritrea, Ethiopia, Libya, Mali, Somalia, South Sudan, Sudan, Zimbabwe\nAmericas:\n Cuba, Nicaragua, Venezuela\nAsia:\n Afghanistan, Burma / Myanmar, Lebanon, North Korea, Syria, Yemen\nEurope:\n Albania, Belarus, Russia, Ukraine\nOceania:\n Fiji\nSouth America Exception:\n Brazil (Visa only)",
  },
  additionalRequirements: { userIdRequired: false },
};

export const dummyCardSandbox = {
  productId: 13959,
  productName: "Vanilla® eGift Visa",
  global: false,
  status: "ACTIVE",
  supportsPreOrder: true,
  senderFee: 6,
  senderFeePercentage: 0,
  discountPercentage: 0,
  denominationType: "RANGE",
  recipientCurrencyCode: "USD",
  minRecipientDenomination: 20,
  maxRecipientDenomination: 100,
  senderCurrencyCode: "USD",
  minSenderDenomination: 20,
  maxSenderDenomination: 100,
  fixedRecipientDenominations: [],
  fixedSenderDenominations: null,
  fixedRecipientToSenderDenominationsMap: null,
  metadata: null,
  logoUrls: ["https://cdn.reloadly.com/giftcards/cdf0a915-a88d-4eb5-8cb8-a4fd00accc7eVanilla.jpg"],
  brand: { brandId: 95, brandName: "Vanilla® eGift Visa" },
  category: { id: 1, name: "Payment Cards" },
  country: { isoName: "US", name: "United States", flagUrl: "https://s3.amazonaws.com/rld-flags/us.svg" },
  redeemInstruction: {
    concise: "To redeem, visit yourrewardcard.com",
    verbose:
      "Virtual Account is a prepaid Virtual Account loaded by the Corporate Sponsor, redeemable to buy goods and services anywhere Visa debit Virtual Accounts are accepted, as described in the Virtual Account Use and Fees section. The Virtual Account is NOT a credit card. The Virtual Account is not a checking account or connected in any way to any account other than a stored value account where your funds are held. The expiration date of the Virtual Account and the Virtual Account funds is identified on the Virtual Account. &#13;eReward Visa Virtual Accountholder Agreement CUSTOMER SERVICE CONTACT INFORMATION: &#13;Address: P.O. Box 826 Fortson, GA 31808 &#13;Website: YourRewardCard.com &#13;Phone Number: 1-833-634-3155",
  },
  additionalRequirements: { userIdRequired: false },
};
