name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        # with:
        # submodules: "recursive" # Ensures submodules are checked out

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Build
        run: |
          yarn
          yarn build
        env: # Set environment variables for the build
          SUPABASE_URL: "https://wfzpewmlyiozupulbuur.supabase.co"
          SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmenBld21seWlvenVwdWxidXVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTU2NzQzMzksImV4cCI6MjAxMTI1MDMzOX0.SKIL3Q0NOBaMehH0ekFspwgcu3afp3Dl9EDzPqs1nKs"
          BACKEND_URL: ""
          OPENROUTER_API_KEY: "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"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: full-stack-app
          path: |
            static
            functions
            shared
            package.json
            yarn.lock
