name: Generate Permit

on:
  workflow_dispatch:
    inputs:
      beneficiary:
        required: true
        description: The address of the beneficiary's wallet
      amount:
        required: true
        description: The amount of permit
      evmPrivateEncrypted:
        required: true
        description: Ubiquibot's Private Key

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.3

      - name: Generate Claimable Permit
        run: |
          HUSKY=0 bun install --frozen-lockfile --registry=https://registry.npmjs.org
          bun run start:sign
        env:
          BENEFICIARY_ADDRESS: ${{ github.event.inputs.beneficiary }}
          PAYMENT_TOKEN_ADDRESS: "0xC6ed4f520f6A4e4DC27273509239b7F8A68d2068"
          AMOUNT_IN_ETH: ${{ github.event.inputs.amount }}
          CHAIN_ID: 100
          FRONTEND_URL: "http://localhost:8080"
          BACKEND_URL: ""
          RPC_PROVIDER_URL: "https://rpc.ankr.com/gnosis"
          UBIQUIBOT_PRIVATE_KEY: ${{ github.event.inputs.evmPrivateEncrypted }}
